from src.relation import load_area

cities = [
    # 'Vienna, Austria',
    # 'Antwerp, Belgium',
    # 'Brussels, Belgium',
    # 'Greater Nicosia, Nicosia District, Cyprus',
    # 'Ostrava, Czechia',
    # 'Prague, Czechia',
    # 'Brno, Czechia',
    # 'Helsinki, Finland',
    # 'Lyon, France',
    # 'Marseille, France',
    # 'Paris, France',
    # 'Bordeaux, France',
    # 'Strasbourg, France',
    # 'Dijon, France',
    # 'Toulouse, France',
    # 'Nantes, France',
    # 'Berlin, DE',
    # 'Cologne, Germany',
    # 'Dresden, Germany',
    # 'Düsseldorf, Germany',
    # 'Dortmund, Germany',
    # 'Frankfurt am Main, Germany',
    # # 'Hamburg, Germany',
    # 'Hannover, Germany',
    # # 'Leipzig, Germany', # rather delete
    # 'Munich, Germany',
    # # 'Stuttgart, Germany',
    # # 'Corfu, Greece',
    # 'Budapest, Hungary',
    # 'Cork, Ireland',
    # 'Dublin, Ireland',
    # 'Galway, Ireland',
    # # 'Florence, Italy',
    # 'Milan, Italy',
    # 'Padua, Italy',
    # # 'Rome, Italy',
    # 'Turin, Italy',
    # 'Luxembourg City',
    # 'Riga, Latvia',
    # 'Vilnius, Lithuania',
    # # 'Amsterdam, Netherlands',
    # # 'Rotterdam, South Holland, Netherlands',
    # # 'The Hague, Netherlands',
    # 'Oslo, Norway',
    # 'Trondheim, Norway',
    # # 'Katowice, Poland',
    # # 'Kraków, Poland',
    # # 'Łódź, Poland',
    # 'Poznań, Poland',
    # 'Szczecin, Poland',
    # 'Warsaw, Poland',
    # 'Wrocław, Poland',
    # # 'Lisbon, Portugal',
    # 'Bucharest, Romania',
    # 'Bratislava, Slovakia',
    # 'Ljubljana, Slovenia',
    # # 'Córdoba, Spain',
    # 'Palma, Spain',
    # 'Valencia, Spain',
    # 'Barcelona, Spain',
    # 'Madrid, Spain',
    # 'Girona, Spain',
    # # 'Santander, Spain',
    # 'Zaragoza, Spain',
    # 'Seville, Spain',
    # 'Municipality Göteborgs Stad, Västra Götaland County, Sweden',
    # 'Malmö, Sweden',
    # # 'Stockholms kommun, Stockholm County, Sweden',
    # 'Lausanne, Switzerland',
    # 'Bern, Switzerland',
    # 'Luzern, Switzerland',
    # 'Kyiv, Ukraine',
    # # 'Lviv, Ukraine',
    # # 'Bristol, UK',
    # 'Cardiff, Wales, CF, United Kingdom',
    # 'Glasgow City, UK',
    # 'Edinburgh, UK',
    # 'Liverpool, UK',
    # # 'Cambridge, UK',
    # 'Greater London, UK',
    # 'Moscow, Russia',
    # # 'Saint Petersburg, Russia',
    # 'Villeurbanne, France',
    # 'Le Bouscat, France',
    1663048,
    105270
]
for city in cities:
    relation = load_area(city)
    if relation is not None:
        relation.load_relations_to_mongo(connection_string = 'mongodb://localhost:27017/')
